--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-1.pgdg110+1)
-- Dumped by pg_dump version 15.8 (Debian 15.8-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: avaliacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avaliacao (
    id bigint NOT NULL,
    comentario character varying(255),
    nota double precision,
    tipo character varying(255),
    avaliado_id bigint,
    avaliador_id bigint,
    reserva_id bigint,
    CONSTRAINT avaliacao_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['MOTORISTA_AVALIA_PASSAGEIRO'::character varying, 'PASSAGEIRO_AVALIA_MOTORISTA'::character varying])::text[])))
);


ALTER TABLE public.avaliacao OWNER TO postgres;

--
-- Name: avaliacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avaliacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avaliacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carona (
    id bigint NOT NULL,
    data date,
    hora time(0) without time zone,
    notificado1h boolean,
    notificado30min boolean,
    qnt_assentos integer NOT NULL,
    realizado boolean NOT NULL,
    status_carona character varying(255),
    vagas_disponiveis integer NOT NULL,
    carro_id bigint,
    user_id bigint,
    rota_id bigint,
    CONSTRAINT carona_status_carona_check CHECK (((status_carona)::text = ANY ((ARRAY['EM_ESPERA'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDA'::character varying, 'CANCELADA'::character varying])::text[])))
);


ALTER TABLE public.carona OWNER TO postgres;

--
-- Name: carona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carro (
    id bigint NOT NULL,
    ano integer,
    ar_condicionado boolean,
    ativo boolean,
    cor character varying(255),
    descricao character varying(255),
    foto_veiculo character varying(255),
    marca character varying(255),
    modelo character varying(255),
    placa character varying(255) NOT NULL,
    vagas integer,
    dono_id bigint,
    CONSTRAINT carro_ano_check CHECK (((ano >= 1900) AND (ano <= 2100))),
    CONSTRAINT carro_vagas_check CHECK (((vagas >= 1) AND (vagas <= 7)))
);


ALTER TABLE public.carro OWNER TO postgres;

--
-- Name: carro_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    motorista_id bigint,
    passageiro_id bigint
);


ALTER TABLE public.chat OWNER TO postgres;

--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faculdade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculdade (
    id bigint NOT NULL,
    localizacao public.geometry(Point,4326),
    nome character varying(255)
);


ALTER TABLE public.faculdade OWNER TO postgres;

--
-- Name: faculdade_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculdade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculdade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensagem (
    id bigint NOT NULL,
    enviado_em timestamp(6) without time zone,
    mensagem character varying(255),
    autor_id bigint,
    chat_id bigint
);


ALTER TABLE public.mensagem OWNER TO postgres;

--
-- Name: mensagem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido_carona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido_carona (
    id bigint NOT NULL,
    data_pedido date,
    destino public.geometry(Point,4326),
    saida public.geometry(Point,4326),
    status character varying(255),
    carona_id bigint,
    passageiro_id bigint,
    CONSTRAINT pedido_carona_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ACEITO'::character varying, 'RECUSADO'::character varying, 'CANCELADO'::character varying])::text[])))
);


ALTER TABLE public.pedido_carona OWNER TO postgres;

--
-- Name: pedido_carona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido_carona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_carona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preferencias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preferencias (
    id bigint NOT NULL,
    animais character varying(255),
    cigarro character varying(255),
    conversa character varying(255),
    musica character varying(255),
    user_id bigint,
    CONSTRAINT preferencias_animais_check CHECK (((animais)::text = ANY ((ARRAY['NUNCA'::character varying, 'TALVEZ'::character varying, 'SEM_PROBLEMA'::character varying])::text[]))),
    CONSTRAINT preferencias_cigarro_check CHECK (((cigarro)::text = ANY ((ARRAY['NUNCA'::character varying, 'TALVEZ'::character varying, 'SEM_PROBLEMA'::character varying])::text[]))),
    CONSTRAINT preferencias_conversa_check CHECK (((conversa)::text = ANY ((ARRAY['NUNCA'::character varying, 'TALVEZ'::character varying, 'SEM_PROBLEMA'::character varying])::text[]))),
    CONSTRAINT preferencias_musica_check CHECK (((musica)::text = ANY ((ARRAY['NUNCA'::character varying, 'TALVEZ'::character varying, 'SEM_PROBLEMA'::character varying])::text[])))
);


ALTER TABLE public.preferencias OWNER TO postgres;

--
-- Name: preferencias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.preferencias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preferencias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reserva (
    id bigint NOT NULL,
    aprovado boolean NOT NULL,
    destino public.geometry(Point,4326),
    ja_enviado_codigo_fim boolean NOT NULL,
    ja_enviado_codigo_inicio boolean NOT NULL,
    saida public.geometry(Point,4326),
    carona_id bigint,
    user_id bigint
);


ALTER TABLE public.reserva OWNER TO postgres;

--
-- Name: reserva_codigo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reserva_codigo (
    id bigint NOT NULL,
    codigo_desembarque character varying(255),
    codigo_embarque character varying(255),
    criado_em timestamp(6) without time zone,
    desembarque_liberado boolean NOT NULL,
    desembarque_realizado boolean NOT NULL,
    embarque_liberado boolean NOT NULL,
    embarque_realizado boolean NOT NULL,
    reserva_id bigint
);


ALTER TABLE public.reserva_codigo OWNER TO postgres;

--
-- Name: reserva_codigo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reserva_codigo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_codigo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reserva_evento (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    tipo_evento character varying(255),
    reserva_id bigint,
    CONSTRAINT reserva_evento_tipo_evento_check CHECK (((tipo_evento)::text = ANY ((ARRAY['EMBARQUE_LIBERADO'::character varying, 'EMBARCADO'::character varying, 'DESEMBARQUE_LIBERADO'::character varying, 'DESEMBARCADO'::character varying, 'NAO_COMPARECEU'::character varying])::text[])))
);


ALTER TABLE public.reserva_evento OWNER TO postgres;

--
-- Name: reserva_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reserva_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rota; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rota (
    id bigint NOT NULL,
    destino public.geometry(Point,4326),
    destino_texto character varying(255),
    distancia double precision,
    duracao double precision,
    saida public.geometry(Point,4326),
    saida_texto character varying(255),
    trajeto public.geometry(LineString,4326)
);


ALTER TABLE public.rota OWNER TO postgres;

--
-- Name: rota_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rota_point; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rota_point (
    id bigint NOT NULL,
    index_order integer NOT NULL,
    localizacao public.geometry(Point,4326),
    rota_id bigint
);


ALTER TABLE public.rota_point OWNER TO postgres;

--
-- Name: rota_point_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rota_point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rota_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    conta_nao_bloqueada boolean NOT NULL,
    conta_nao_expirada boolean NOT NULL,
    cpf character varying(255),
    credenciais_nao_expiradas boolean NOT NULL,
    data_nascimento date,
    foto character varying(255),
    genero character varying(255),
    nome character varying(255),
    password character varying(255),
    telefone character varying(255),
    token character varying(255),
    username character varying(255) NOT NULL,
    preferencia_id bigint,
    CONSTRAINT users_genero_check CHECK (((genero)::text = ANY ((ARRAY['MASCULINO'::character varying, 'FEMININO'::character varying, 'OUTROS'::character varying, 'NAO_INFORMADO'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: avaliacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avaliacao (id, comentario, nota, tipo, avaliado_id, avaliador_id, reserva_id) FROM stdin;
\.


--
-- Data for Name: carona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carona (id, data, hora, notificado1h, notificado30min, qnt_assentos, realizado, status_carona, vagas_disponiveis, carro_id, user_id, rota_id) FROM stdin;
1	2026-05-20	12:00:00	f	f	5	f	\N	5	\N	1	1
\.


--
-- Data for Name: carro; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carro (id, ano, ar_condicionado, ativo, cor, descricao, foto_veiculo, marca, modelo, placa, vagas, dono_id) FROM stdin;
\.


--
-- Data for Name: chat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat (id, criado_em, motorista_id, passageiro_id) FROM stdin;
\.


--
-- Data for Name: faculdade; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faculdade (id, localizacao, nome) FROM stdin;
\.


--
-- Data for Name: mensagem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mensagem (id, enviado_em, mensagem, autor_id, chat_id) FROM stdin;
\.


--
-- Data for Name: pedido_carona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedido_carona (id, data_pedido, destino, saida, status, carona_id, passageiro_id) FROM stdin;
1	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	17
2	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	27
3	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	8
4	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	12
5	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	5
6	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	2
7	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	34
8	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	10
9	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	38
10	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	48
11	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	7
12	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	43
13	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	45
14	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	4
15	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	25
16	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	46
17	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	40
18	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	28
19	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	51
20	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	41
21	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	39
22	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	47
23	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	31
24	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	36
25	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	44
26	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	24
27	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	32
28	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	37
29	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	26
30	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	29
31	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	49
32	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	6
33	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	14
34	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	16
35	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	3
36	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	15
37	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	33
38	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	13
39	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	35
40	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	11
41	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	30
42	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	18
43	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	23
44	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	21
45	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	22
46	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	42
47	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	20
48	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	50
49	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	19
50	2026-05-16	0101000020E610000086E9D6C6337B46C083E222522E9636C0	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	PENDENTE	1	9
\.


--
-- Data for Name: preferencias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.preferencias (id, animais, cigarro, conversa, musica, user_id) FROM stdin;
1	TALVEZ	TALVEZ	TALVEZ	TALVEZ	1
2	TALVEZ	TALVEZ	TALVEZ	TALVEZ	66
\.


--
-- Data for Name: reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reserva (id, aprovado, destino, ja_enviado_codigo_fim, ja_enviado_codigo_inicio, saida, carona_id, user_id) FROM stdin;
\.


--
-- Data for Name: reserva_codigo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reserva_codigo (id, codigo_desembarque, codigo_embarque, criado_em, desembarque_liberado, desembarque_realizado, embarque_liberado, embarque_realizado, reserva_id) FROM stdin;
\.


--
-- Data for Name: reserva_evento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reserva_evento (id, criado_em, tipo_evento, reserva_id) FROM stdin;
\.


--
-- Data for Name: rota; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rota (id, destino, destino_texto, distancia, duracao, saida, saida_texto, trajeto) FROM stdin;
1	0101000020E610000086E9D6C6337B46C083E222522E9636C0	Avenida Rotary 383, Cruzeiro, SP, Brazil	8.66	12.68	0101000020E61000008ECEF9298E7346C0011764CBF29136C0	Rua Professor Pedro Nascevicios, Lavrinhas, SP, Brazil	0102000020E61000009500000028D53E1D8F7346C0F4346090F49136C0C460FE0A997346C06E4C4F58E29136C0A83462669F7346C002452C62D89136C0815A0C1EA67346C074CFBA46CB9136C0BBF083F3A97346C00A302C7FBE9136C01AF9BCE2A97346C01F9F909DB79136C0ED10FFB0A57346C047CA1649BB9136C0575F5D15A87346C0AA0A0DC4B29136C0253FE257AC7346C09291B3B0A79136C0535BEA20AF7346C0D8B8FE5D9F9136C0CF488446B07346C0A4AB74779D9136C051BF0B5BB37346C08DB7955E9B9136C014252191B67346C0FA0967B7969136C0962023A0C27346C0E9B5D958899136C0E1ED4108C87346C049A12C7C7D9136C061191BBAD97346C00CB08F4E5D9136C08E1EBFB7E97346C0B7627FD93D9136C0B81FF0C0007446C04F594DD7139136C0946C7539257446C050ABE80FCD9036C0BD1C76DF317446C02B33A5F5B79036C03CF71E2E397446C0A7CF0EB8AE9036C0501BD5E9407446C0F2B391EBA69036C0C4E8B985AE7446C08CBB41B4569036C08907944DB97446C09DD5027B4C9036C084674293C47446C091D61874429036C01A6A1492CC7446C0CFD8976C3C9036C09032E202D07446C0D6FD63213A9036C0BB7EC16ED87446C0EC6CC83F339036C089D2DEE00B7546C054ABAFAE0A9036C0D658C2DA187546C0FF976BD1029036C00E87A5811F7546C0548EC9E2FE8F36C064CE33F6257546C0A81C93C5FD8F36C0096CCEC1337546C02DE8BD31049036C08693347F4C7546C0B4386398139036C0B79C4B71557546C036AFEAAC169036C03677F4BF5C7546C0A13193A8179036C096D05D12677546C07D5BB054179036C0AE49B725727546C0AD1397E3159036C0F1BDBF417B7546C091628044139036C079B0C56E9F7546C0C0B2D2A4149036C024287E8CB97546C037177FDB139036C02A70B20DDC7546C0A8565F5D159036C02B1213D4F07546C0B98D06F0169036C0BA8784EFFD7546C07636E49F199036C081423D7D047646C00F09DFFB1B9036C0352A70B20D7646C09E616A4B1D9036C03F709527107646C0D993C0E61C9036C0A13193A8177646C02A52616C219036C0AFCC5B751D7646C0BE672442239036C04E2844C0217646C09FE6E445269036C0C3F01131257646C08522DDCF299036C0081EDFDE357646C0AA7D3A1E339036C03EB0E3BF407646C0B77C24253D9036C066DB696B447646C0F7031E18409036C0056B9C4D477646C055A4C2D8429036C07A8A1C226E7646C0E9F351465C9036C06117450F7C7646C02A00C633689036C028BB99D18F7646C0683C11C4799036C04A97FE25A97646C0F1113125929036C03F6EBF7CB27646C0E71C3C139A9036C0272F3201BF7646C009A87004A99036C0E23B31EBC57646C076172829B09036C04B3FE1ECD67646C0508E0244C19036C03999B855107746C0BB09BE69FA9036C0AA29C93A1C7746C0F9C08EFF029136C0FF08C380257746C00E4DD9E9079136C0697407B1337746C0BE13B35E0C9136C0FD31AD4D637746C08466D7BD159136C0C443183F8D7746C0637D03931B9136C07444BE4BA97746C0ED80EB8A199136C06B0E10CCD17746C08B8BA372139136C0D1419770E87746C05DA3E5400F9136C0662D05A4FD7746C0E2E995B20C9136C0CDC82077117846C07E8CB96B099136C07940D9942B7846C0BB26A435069136C0613596B0367846C08CD651D5049136C0BFF2203D457846C07B9FAA42039136C012876C205D7846C05FEE93A3009136C0E75086AA987846C0F73B1405FA9036C07B4FE5B4A77846C0A515DF50F89036C0E5284014CC7846C07270E998F39036C0AB984A3FE17846C00E130D52F09036C0BADBF5D2147946C0FAEE5696E89036C07B6AF5D5557946C070CE88D2DE9036C0CA17B490807946C09F01F566D49036C06B2C616D8C7946C0CAFCA36FD29036C05FCFD72C977946C0A1698995D19036C08A0453CDAC7946C05E126745D49036C0451152B7B37946C0F38FBE49D39036C05BD1E638B77946C09BAC510FD19036C0E8C1DD59BB7946C01B9E5E29CB9036C06A6CAF05BD7946C07651F4C0C79036C0F2D3B837BF7946C0BF654E97C59036C01A33897AC17946C0D7C1C1DEC49036C0130EBDC5C37946C07D76C075C59036C02A029CDEC57946C0118C834BC79036C06ABDDF68C77946C08D45D3D9C99036C0EC67B114C97946C0D7DEA7AAD09036C042AF3F89CF7946C077F35487DC9036C0418177F2E97946C0FE7DC685039136C09F724C16F77946C08C101E6D1C9136C09CA223B9FC7946C0D27135B22B9136C0AB3DEC85027A46C03FFED2A23E9136C0D3687231067A46C067463F1A4E9136C08597E0D4077A46C0172AFF5A5E9136C0C4EA8F300C7A46C09BAA7B64739136C0E78C28ED0D7A46C08CF84ECC7A9136C0892650C4227A46C0064A0A2C809136C0EE258DD13A7A46C01BD65416859136C01C5F7B66497A46C06C94F59B899136C042EE224C517A46C076A6D0798D9136C06D3A02B8597A46C0CBB91457959136C033C170AE617A46C073F38DE89E9136C0077B1343727A46C0ECF99AE5B29136C064963D096C7A46C0C11BD2A8C09136C050C3B7B06E7A46C09CFA40F2CE9136C00377A04E797A46C0774D486B0C9236C0F7949C137B7A46C0DD9733DB159236C0EDF0D7648D7A46C01C075E2D779236C05CE509849D7A46C023F77475C79236C03673486AA17A46C0DDEC0F94DB9236C0A1F5F065A27A46C0755776C1E09236C0E9263108AC7A46C04968CBB9149336C0EE98BA2BBB7A46C0F77475C7629336C09A27D714C87A46C0A4FCA4DAA79336C0894160E5D07A46C0E0A293A5D69336C09F1EDB32E07A46C04DC0AF91249436C020B24813EF7A46C02B85402E719436C0395FECBDF87A46C03F1D8F19A89436C02711E15F047B46C04E7D2079E79436C0CEE2C5C2107B46C0FD6CE4BA299536C0B11A4B581B7B46C06BB8C83D5D9536C0215A2BDA1C7B46C01A170E84649536C0B003E78C287B46C02DAF5C6F9B9536C0AA6395D2337B46C069723106D69536C07B30293E3E7B46C0F2E9B12D039636C008556AF6407B46C0B1170AD80E9636C0E2AE5E45467B46C045679945289636C0B7B3AF3C487B46C06CAF05BD379636C0B7B3AF3C487B46C0B1A888D3499636C04D6551D8457B46C013BBB6B75B9636C07F68E6C9357B46C091D5AD9E939636C06F6589CE327B46C0C8EC2C7AA79636C0D13DEB1A2D7B46C066F7E461A19636C0B2BCAB1E307B46C02CF3565D879636C0359BC761307B46C0A9DA6E826F9636C07C7BD7A02F7B46C009C6C1A5639636C0AD33BE2F2E7B46C04A9869FB579636C04B3E7617287B46C0D3DC0A61359636C0
\.


--
-- Data for Name: rota_point; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rota_point (id, index_order, localizacao, rota_id) FROM stdin;
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, ativo, conta_nao_bloqueada, conta_nao_expirada, cpf, credenciais_nao_expiradas, data_nascimento, foto, genero, nome, password, telefone, token, username, preferencia_id) FROM stdin;
1	t	t	t	\N	t	\N	\N	NAO_INFORMADO	Admin	$2a$10$ziG4pVy7RLR4NnJUFMfSDO/WSFDaM2md.8OXyV5q9OoJHxsClfIxW	\N	\N	admin@gmail.com	1
2	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$kcPmhCj7Zyfbv2NrC/3mS.1f4XtmWm8KuFj509Erop1RbOFWO1k5K	\N	\N	user1@gmail.com	\N
3	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$2M/nP0q/rrMDG495eafSfO87aIt1WBMVnijUoRkbLhsMIiffovfra	\N	\N	user2@gmail.com	\N
4	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$i.pzOJ3SGDMQWKd15dBzHOFClbIEU41QgN64TnCtAk0FqRLtlnhzC	\N	\N	user3@gmail.com	\N
5	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$MBU.5kgjxTp9SyygMYS2rOtMCyQm/71vBhQrhCjHrrGjztRN59REa	\N	\N	user4@gmail.com	\N
6	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$c8eAN1Z/QEzM0qLhbkyxJuyX4jWJXvGUkz5V/iPGtfW0RyPJ//2pO	\N	\N	user5@gmail.com	\N
7	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$vt9X.O87xAxLBLyeJ8oovu5L4BKDoHVQojyPh9bGbf7aH1S68IDw.	\N	\N	user6@gmail.com	\N
8	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$JB3HhLhkcoRtJvQI2vPAwu67xxAqAwcZJSWnyEuYHP7a1EAcf2AXK	\N	\N	user7@gmail.com	\N
9	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$YsI0Rr3QHGUPl4ehajVzwu8.tDmzCVcGVAyS6ASXGkfqCXLygDTSS	\N	\N	user8@gmail.com	\N
10	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$whLtgK0m/jJSivDzNXW97.EcKtpEmHMWRlmZh3gGtl/H.M/nuvEAe	\N	\N	user9@gmail.com	\N
11	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$9nZ6yFq3dFg5mVt/zTGfHuop7cwW4HrHVePy7T6r9tsBY8.6SISom	\N	\N	user10@gmail.com	\N
12	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$ZZGFqLipR6uw5uUliKeDQeHd1TrKR14fuqlVTa2pbNHdEaKG2yzAu	\N	\N	user11@gmail.com	\N
13	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$a3rfPqLR1ReVB0wMPhvOkOHQbY5..ogA5saI5enI7JVbxZf93aBhi	\N	\N	user12@gmail.com	\N
14	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$MmEg/F.0DWdgntW8Mbezx.vajkn3EjmN9Q5iGvodiUMWOtklj6ESa	\N	\N	user13@gmail.com	\N
15	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$rKGsuaS9Rj/0/2YdPR9n7.SqVGdjQUa4nPxBCXxqZtCUnjh7PueRy	\N	\N	user14@gmail.com	\N
16	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$nC/w5eTKuxZCpnP5xLmv/eq05I3YNL1BTZSYK9edmv7S/m5crR2Ju	\N	\N	user15@gmail.com	\N
17	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$rhqsBK0/jq5yOMVycGy53.lPULfHxv56HZR90rKJCuiUQjnnS1vLy	\N	\N	user16@gmail.com	\N
18	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$KaMr2xDLNloGfqpID.gAE.DsBHB9ohAJiJdqvo6Oo02XOyWvsS1Bu	\N	\N	user17@gmail.com	\N
19	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$mOOnyK2vxXWwGCXMTXxAfe2OOSovNVEIkl8NauCiaW.uS6kGkZVdu	\N	\N	user18@gmail.com	\N
20	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$voLof279kSQq0eu8v9YT0.P.3W3nXJv9smVPxGOCKfNIVxWUKZCtu	\N	\N	user19@gmail.com	\N
21	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$KhmFZLrwq5ORy1PwMnGM1uDlGo3zUAXwLT8YV9nPEjU9VrCZ/kwS.	\N	\N	user20@gmail.com	\N
22	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$cauyVUEAVsr.R8clVnTDUuvfcsigIpTkJ3hT6Z2fYWX.vfsLqmwZS	\N	\N	user21@gmail.com	\N
23	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$kWnbNUN0EMcTAT/Ca66n1../oU6dUAInMMWMdIdFPG4K7VE/kuLd2	\N	\N	user22@gmail.com	\N
24	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$oQEtJGcEsyC8Hn.HSGzi3.iiogPGoIavhGmILNaSX7looKjFTYx9C	\N	\N	user23@gmail.com	\N
25	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$T.Y9hpBJAi1VaL77dQfOruakXrQfCfikS6m4yn58T62MVC4fBtFea	\N	\N	user24@gmail.com	\N
26	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$8hfqVQLAppRmZKObl1hch.4OGRupomvnKxfJ/qufMJS3fDoSINXXy	\N	\N	user25@gmail.com	\N
27	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$qkP//LTXMH3GpKAxw3.zau4RTCajUT5TNjS/cXQfdo0j45dO0o9dS	\N	\N	user26@gmail.com	\N
28	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$s/K6QcJ/FMvjhk.9cEmusuOQ4q2iDS49iCjR85sUGJ6vF4DLubfQ2	\N	\N	user27@gmail.com	\N
29	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$aOawd1m3mP/k9rhGKaz8u.i3vQAKDWu/oB8kz.UiUjqTKnz/P12bu	\N	\N	user28@gmail.com	\N
30	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$U5yLdwhUJtum2t2ArJ77qumzHfFQgw3X..2NP7k4w6MuLC7GtV0UG	\N	\N	user29@gmail.com	\N
31	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$R8cYnYrXfDb5jYhUEWFPW.oqakqnJjahkDeA5bk7z/kSz533zn23K	\N	\N	user30@gmail.com	\N
32	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$ElnUsXLuZQ4B0oS.edJND.sWIGZdOlMyBUCApSjeRIvffc0QW2/Pu	\N	\N	user31@gmail.com	\N
33	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$3mS0aYyg/2MdtdFEQ0xIIuavAmxknRj4533x6AiphE33W6O0iS1/S	\N	\N	user32@gmail.com	\N
34	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$ecZrupE/T3.UZL4YheyY0efTEPdDqn/BdMW7U2.uRAhUctaV5hbj.	\N	\N	user33@gmail.com	\N
35	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$YsLR2UVxo57wVZ5dF9zOuup6FExr76HyIZjp1wyRfbQLxUkufzpaS	\N	\N	user34@gmail.com	\N
36	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$qEJp6qW5U3JBkX9DYnUz/.mXsSuEP0hN4gBvnLnGCMl8CgBwJvdiu	\N	\N	user35@gmail.com	\N
37	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$VPAdD5A7ih12giTAbMdgReTP1cC9vjFyIYUu9cMYZZm/8VPmRgYG2	\N	\N	user36@gmail.com	\N
38	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$CpCFCIa1WJl.q3VtipuiAO1fhlXQN4eOWSmy5pvl8p9kJDJERfRzO	\N	\N	user37@gmail.com	\N
39	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$1hVQIFCCJ/hzFKeYmu.BouzM2OkMAjRV4bJv17RTUV6K9K7gmOq9C	\N	\N	user38@gmail.com	\N
40	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$Brb4FifEipS6keChh2H5Z.xbGyFesA9DcTbDPgcIvJN0gnWLit0Zu	\N	\N	user39@gmail.com	\N
41	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$YZdzMbv77cc027Fp0X6cvuJlp8Rm0UHXe22FZFPly2FgPm74fKIba	\N	\N	user40@gmail.com	\N
42	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$80Ki/ILEExFJ8gsdTkvYXOHnA6rK6bD1DlROa61mKTrKc9y1o.fZa	\N	\N	user41@gmail.com	\N
43	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$Cl8BXmkILjyEYvuxy8mzmOc.GStxSa3XZO5O4ZDqJmCW5auNkSQha	\N	\N	user42@gmail.com	\N
44	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$CXPx81mmRScruQL8roCeGOKcKqTa0.43gsIpn9BupZQXEwfzAIURi	\N	\N	user43@gmail.com	\N
45	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$mSeQsqpwaXp1ZAO15U/STuBxaQ/Qzhd5iqioKuSe7bvZbdVf8Nwnq	\N	\N	user44@gmail.com	\N
46	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$noluTFvmIER5b.FRmjG3d.nowEBm6BJ06zXRtRcIvex9taLgafm8O	\N	\N	user45@gmail.com	\N
47	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$jmnbcaN3qlnkuyvxxgv6IenuJvv58fNdWRPSYM9GE7oCg1TmO6XcK	\N	\N	user46@gmail.com	\N
48	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$YY1Ox.wxQ23RE3iqew2QI.AKyqjVi7BbR0khRm3G91HvqpNrsfnfu	\N	\N	user47@gmail.com	\N
49	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$bNEGsewM25tPdR3kGVsmhu3.A38QmU9rMcgx00gn.jVheML6qRPVy	\N	\N	user48@gmail.com	\N
50	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$jgPWMIdB7Ivje5eD2Dz./.MDTSpVShPoMYXABNSo2xG.8.m8eaxsC	\N	\N	user49@gmail.com	\N
51	t	t	t	\N	t	\N	\N	\N	\N	$2a$10$lfv8258ckeQAdsM7tSAupOzOMcl5CvFNVpYaNe6RdCMmTQUITakFq	\N	\N	user50@gmail.com	\N
66	t	t	t	\N	t	\N	\N	NAO_INFORMADO	Bruno	$2a$10$j3mLoKJVZgd7.TeIvedzSeydVunSkXmjwZv.1I6dIEWm.OqJr2x5C	\N	\N	bruno@gmail.com	2
\.


--
-- Name: avaliacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avaliacao_id_seq', 1, false);


--
-- Name: carona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carona_id_seq', 11, true);


--
-- Name: carro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carro_id_seq', 1, false);


--
-- Name: chat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_id_seq', 1, false);


--
-- Name: faculdade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculdade_id_seq', 1, false);


--
-- Name: mensagem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensagem_id_seq', 1, false);


--
-- Name: pedido_carona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_carona_id_seq', 51, true);


--
-- Name: preferencias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.preferencias_id_seq', 2, true);


--
-- Name: reserva_codigo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reserva_codigo_id_seq', 18, true);


--
-- Name: reserva_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reserva_evento_id_seq', 1, false);


--
-- Name: reserva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reserva_id_seq', 18, true);


--
-- Name: rota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rota_id_seq', 4, true);


--
-- Name: rota_point_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rota_point_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 82, true);


--
-- Name: avaliacao avaliacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_pkey PRIMARY KEY (id);


--
-- Name: carona carona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carona
    ADD CONSTRAINT carona_pkey PRIMARY KEY (id);


--
-- Name: carro carro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT carro_pkey PRIMARY KEY (id);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: faculdade faculdade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculdade
    ADD CONSTRAINT faculdade_pkey PRIMARY KEY (id);


--
-- Name: mensagem mensagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT mensagem_pkey PRIMARY KEY (id);


--
-- Name: pedido_carona pedido_carona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_carona
    ADD CONSTRAINT pedido_carona_pkey PRIMARY KEY (id);


--
-- Name: preferencias preferencias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferencias
    ADD CONSTRAINT preferencias_pkey PRIMARY KEY (id);


--
-- Name: reserva_codigo reserva_codigo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_codigo
    ADD CONSTRAINT reserva_codigo_pkey PRIMARY KEY (id);


--
-- Name: reserva_evento reserva_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_evento
    ADD CONSTRAINT reserva_evento_pkey PRIMARY KEY (id);


--
-- Name: reserva reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT reserva_pkey PRIMARY KEY (id);


--
-- Name: rota rota_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rota
    ADD CONSTRAINT rota_pkey PRIMARY KEY (id);


--
-- Name: rota_point rota_point_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rota_point
    ADD CONSTRAINT rota_point_pkey PRIMARY KEY (id);


--
-- Name: reserva_codigo uk13erwlx9q9c0wcixnlu8bwvhf; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_codigo
    ADD CONSTRAINT uk13erwlx9q9c0wcixnlu8bwvhf UNIQUE (reserva_id);


--
-- Name: carro uk5uv3fisdwp2pmj1357rivswea; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT uk5uv3fisdwp2pmj1357rivswea UNIQUE (placa);


--
-- Name: carona ukfw7562cj4k6awjdpyjbi6r6k9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carona
    ADD CONSTRAINT ukfw7562cj4k6awjdpyjbi6r6k9 UNIQUE (rota_id);


--
-- Name: users uknxm5859p33x1fhd5uabg1cn7p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uknxm5859p33x1fhd5uabg1cn7p UNIQUE (preferencia_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: preferencias uks9hrjsr7woqwtn4t53h1ecv7m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferencias
    ADD CONSTRAINT uks9hrjsr7woqwtn4t53h1ecv7m UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: rota_point fk25k67hcwxqu9ld8wkybo6iupv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rota_point
    ADD CONSTRAINT fk25k67hcwxqu9ld8wkybo6iupv FOREIGN KEY (rota_id) REFERENCES public.rota(id);


--
-- Name: carona fk2v3rr7u0qr9ymhgko8o7y79vk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carona
    ADD CONSTRAINT fk2v3rr7u0qr9ymhgko8o7y79vk FOREIGN KEY (rota_id) REFERENCES public.rota(id);


--
-- Name: pedido_carona fk3in596hq4q5ne8lknx62ccaly; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_carona
    ADD CONSTRAINT fk3in596hq4q5ne8lknx62ccaly FOREIGN KEY (carona_id) REFERENCES public.carona(id);


--
-- Name: chat fk5450fas4brka7yfmnid7xnr7e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk5450fas4brka7yfmnid7xnr7e FOREIGN KEY (passageiro_id) REFERENCES public.users(id);


--
-- Name: avaliacao fk548bxp65jmytpkew1iehwtwur; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT fk548bxp65jmytpkew1iehwtwur FOREIGN KEY (reserva_id) REFERENCES public.reserva(id);


--
-- Name: carro fk55ne2oib7hx4kl4s94ccosyfo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carro
    ADD CONSTRAINT fk55ne2oib7hx4kl4s94ccosyfo FOREIGN KEY (dono_id) REFERENCES public.users(id);


--
-- Name: mensagem fk5dvghd3mv72tb4p3j190vqi5s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fk5dvghd3mv72tb4p3j190vqi5s FOREIGN KEY (chat_id) REFERENCES public.chat(id);


--
-- Name: pedido_carona fkb66lsti7amkfhm5lqr8rqdowj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido_carona
    ADD CONSTRAINT fkb66lsti7amkfhm5lqr8rqdowj FOREIGN KEY (passageiro_id) REFERENCES public.users(id);


--
-- Name: carona fkcq4n2wxww8eyv9ckxthqa3i5c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carona
    ADD CONSTRAINT fkcq4n2wxww8eyv9ckxthqa3i5c FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users fkec5l8l31m6xey96x8pxf5yf3j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkec5l8l31m6xey96x8pxf5yf3j FOREIGN KEY (preferencia_id) REFERENCES public.preferencias(id);


--
-- Name: reserva_evento fkfy617cdo2346i4h3q38mprn2y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_evento
    ADD CONSTRAINT fkfy617cdo2346i4h3q38mprn2y FOREIGN KEY (reserva_id) REFERENCES public.reserva(id);


--
-- Name: reserva fkhmujhtofywl7lbc98lyfbx776; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT fkhmujhtofywl7lbc98lyfbx776 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: mensagem fkmjq8vuj0ydghwt5x5egsuvusr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fkmjq8vuj0ydghwt5x5egsuvusr FOREIGN KEY (autor_id) REFERENCES public.users(id);


--
-- Name: reserva_codigo fknquxls42v65mrcsgioi1houom; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva_codigo
    ADD CONSTRAINT fknquxls42v65mrcsgioi1houom FOREIGN KEY (reserva_id) REFERENCES public.reserva(id);


--
-- Name: carona fkobwps9k8d7hijbwll9w7leaee; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carona
    ADD CONSTRAINT fkobwps9k8d7hijbwll9w7leaee FOREIGN KEY (carro_id) REFERENCES public.carro(id);


--
-- Name: chat fkosrsf0jrmwivp7nwoviavdmya; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fkosrsf0jrmwivp7nwoviavdmya FOREIGN KEY (motorista_id) REFERENCES public.users(id);


--
-- Name: avaliacao fkqp9gbvaskxqryyxdvqfbvttov; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT fkqp9gbvaskxqryyxdvqfbvttov FOREIGN KEY (avaliador_id) REFERENCES public.users(id);


--
-- Name: preferencias fkqvfms2otn46pw8v6avbsiewfw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preferencias
    ADD CONSTRAINT fkqvfms2otn46pw8v6avbsiewfw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reserva fkrn5mjr32xl94lffwpq1q4gxb4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT fkrn5mjr32xl94lffwpq1q4gxb4 FOREIGN KEY (carona_id) REFERENCES public.carona(id);


--
-- Name: avaliacao fkrt31ft3nbug0hd8r1mlujdeow; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT fkrt31ft3nbug0hd8r1mlujdeow FOREIGN KEY (avaliado_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

